import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { createServer } from 'vite';

const root = new URL('../', import.meta.url);
const read = (path) => readFile(new URL(path, root), 'utf8');

async function load() {
  process.env.VITE_SUPABASE_URL = 'https://synthetic.invalid';
  process.env.VITE_SUPABASE_ANON_KEY = 'synthetic-test-key';
  // react-router-dom only re-exports react-router and ships as CommonJS, which Node cannot import by name: the test uses react-router directly. React itself stays the one Node loads.
  const server = await createServer({ root: root.pathname, server: { middlewareMode: true }, appType: 'custom', logLevel: 'silent', resolve: { alias: { 'react-router-dom': 'react-router' } }, ssr: { noExternal: ['react-router'] } });
  const get = (path) => server.ssrLoadModule(path);
  return {
    ...(await get('/src/legal/richText.ts')),
    ...(await get('/src/legal/markers.ts')),
    ...(await get('/src/legal/placeholders.ts')),
    ...(await get('/src/legal/terms.ts')),
    ...(await get('/src/legal/privacy.ts')),
    get,
    close: () => server.close(),
  };
}

const text = (doc, allStrings) => allStrings(doc).join('\n');

test('inline markup: bold, links, TODO (open and filled), confirm flags and unknown keys', async () => {
  const { parseInline, todoKeys, confirmFlags, close } = await load();
  try {
    assert.deepEqual(parseInline('a **b** [c](/terms) {{TODO:ENTITY_NAME}} {{CONFIRM: check this }} d').map((s) => s.kind), ['text', 'bold', 'text', 'link', 'text', 'todo', 'text', 'confirm', 'text']);
    assert.deepEqual(parseInline('{{TODO:NOT_A_KEY}}'), [{ kind: 'todo', key: 'NOT_A_KEY', label: 'NOT_A_KEY' }], 'an unknown key stays visible instead of vanishing');
    assert.equal(parseInline('{{TODO:ENTITY_NAME}}')[0].kind, 'todo');
    assert.deepEqual(todoKeys('{{TODO:A_B}} x {{TODO:C1}}'), ['A_B', 'C1']);
    assert.deepEqual(confirmFlags('{{CONFIRM: one }} {{CONFIRM:two}}'), ['one', 'two']);
    assert.deepEqual(parseInline('plain'), [{ kind: 'text', text: 'plain' }]);
  } finally { await close(); }
});

test('every missing detail is a registered placeholder, and nothing registered is unused: no invented values', async () => {
  const { PLACEHOLDERS, TERMS, PRIVACY, allStrings, todoKeys, close } = await load();
  try {
    const used = new Set([...allStrings(TERMS), ...allStrings(PRIVACY)].flatMap(todoKeys));
    for (const key of used) assert.ok(PLACEHOLDERS[key], `${key} is used but not registered`);
    for (const key of Object.keys(PLACEHOLDERS)) assert.ok(used.has(key) || key === 'EFFECTIVE_DATE', `${key} is registered but not used`);
    for (const [key, entry] of Object.entries(PLACEHOLDERS)) {
      assert.ok(entry.label.length > 5 && entry.question.length > 20, `${key} needs a label and a question`);
      assert.ok(entry.value === null || (typeof entry.value === 'string' && entry.value.trim().length > 0), `${key} must be null or a real answer`);
    }
  } finally { await close(); }
});

test('the Terms cover every topic that was asked for', async () => {
  const { TERMS, allStrings, close } = await load();
  try {
    const all = text(TERMS, allStrings);
    const topics = {
      'accounts and security': /Your account and its security/,
      'minimum age': /at least 18/,
      'Roleplay': /\bRoleplay\b/, 'Storytelling': /\bStorytelling\b/,
      'AI-generated interactions': /generated by AI models|AI can be wrong/,
      'user-generated content': /Your content/,
      'ownership stays with the user': /keep ownership of your content/,
      'licence limited to what is needed': /non-exclusive, royalty-free licence[^]*only as needed/,
      'acceptable use': /Rules: what you must not do/,
      'moderation, reports, suspension, termination': /Reports, moderation and enforcement[^]*Ending your account|suspend your account/,
      'subscriptions': /Subscriptions and other paid features/,
      'SHARDS': /SHARDS/, 'VELLUM': /VELLUM/,
      'virtual and spend-only': /virtual and spend-only/,
      'no bank or deposit account': /does not open a bank account, a deposit account/,
      'no redemption for cash': /cannot redeem them for cash|cannot withdraw, exchange or cash out/,
      'creator support': /Supporting creators/,
      'separate Creator Earnings balance': /Creator Earnings[^]*separate balance/,
      'payouts and eligibility': /Payouts[^]*Eligibility|Eligibility[^]*Payouts/,
      'platform fees': /platform fee/i, 'payment-processing fees': /payment-processing fees/i,
      'taxes': /Taxes/, 'refunds': /Refunds/, 'chargebacks': /Chargebacks/,
      'third-party payment providers': /Payment providers/,
      'IP complaints': /intellectual-property complaints/,
      'disclaimers': /Disclaimers/, 'limit of liability': /Limit of liability/,
      'changes to the service and Terms': /Changes to the service and to these Terms/,
      'governing law': /Governing law and disputes/,
    };
    for (const [name, pattern] of Object.entries(topics)) assert.match(all, pattern, `Terms: missing "${name}"`);
  } finally { await close(); }
});

test('the Privacy Policy covers every topic that was asked for', async () => {
  const { PRIVACY, allStrings, close } = await load();
  try {
    const all = text(PRIVACY, allStrings);
    const topics = {
      'account and profile information': /Account and sign-in[^]*Profile/,
      'authentication data': /password[^]*hashed/,
      'user-generated content and messages': /What you create[^]*Roleplay and storytelling data/,
      'payment and transaction information': /Payments and credits/,
      'creator payout information': /Creator payout information/,
      'device, technical, security and usage data': /Device, technical and security data/,
      'cookies and local storage': /Cookies and local storage/,
      'why each category is processed': /Why we use it/,
      'retention': /How long we keep data/,
      'account deletion': /Deleting your account and data/,
      'access, export, correction': /Access[^]*Correct[^]*Delete/,
      'security practices': /How we protect your data/,
      'Supabase': /Supabase/, 'payment provider': /Stripe/,
      'international transfers': /Transfers outside your country/,
      'minors': /Children/,
      'contact': /Contact/,
      'jurisdiction rights': /GDPR[^]*US state laws|US state laws[^]*GDPR/,
      'AI providers': /Google[^]*OpenRouter/,
    };
    for (const [name, pattern] of Object.entries(topics)) assert.match(all, pattern, `Privacy: missing "${name}"`);
  } finally { await close(); }
});

test('the drafts never claim to be lawyer-approved or guaranteed compliant, and the page says so itself', async () => {
  const { TERMS, PRIVACY, allStrings, close } = await load();
  try {
    const all = [text(TERMS, allStrings), text(PRIVACY, allStrings)].join('\n');
    assert.ok(!/lawyer[- ]approved|legally (compliant|guaranteed)|guaranteed to comply|fully compliant|GDPR[- ]compliant|CCPA[- ]compliant/i.test(all));
    const view = await read('src/components/legal/LegalDocumentView.tsx');
    assert.match(view, /not legal advice/);
    assert.match(view, /not been reviewed by a lawyer/);
    assert.match(view, /DRAFT, NOT YET IN FORCE/);
  } finally { await close(); }
});

test('the documents match what the code does today (so a change in the code fails here until the text is updated)', async () => {
  const { TERMS, PRIVACY, allStrings, close } = await load();
  try {
    const terms = text(TERMS, allStrings);
    const privacy = text(PRIVACY, allStrings);

    // Age: the sign-up says 18, so do both documents.
    assert.match(await read('src/pages/AuthPage.tsx'), /18 years old or older/);
    assert.match(terms, /at least 18/); assert.match(privacy, /18 and over/);

    // Browser storage: exactly these files use it, and nothing sets cookies or uses IndexedDB.
    const files = [];
    const walk = async (dir) => {
      for (const entry of await readdir(new URL(dir, root), { withFileTypes: true })) {
        if (entry.isDirectory()) await walk(`${dir}${entry.name}/`);
        else if (/\.(ts|tsx)$/.test(entry.name)) files.push(`${dir}${entry.name}`);
      }
    };
    await walk('src/');
    const using = (needle) => { const hits = []; return Promise.all(files.map(async (f) => { if ((await read(f)).includes(needle)) hits.push(f); })).then(() => hits.sort()); };
    assert.deepEqual(await using('localStorage'), ['src/contexts/ModeContext.tsx', 'src/lib/chatLook.ts', 'src/lib/draftJournal.ts', 'src/lib/panelPrefs.ts'], 'new use of localStorage: update the Privacy Policy');
    assert.deepEqual(await using('sessionStorage'), ['src/pages/ShardsPage.tsx'], 'new use of sessionStorage: update the Privacy Policy');
    assert.deepEqual(await using('document.cookie'), [], 'cookies are now set by the code: update the Privacy Policy');
    assert.deepEqual(await using('indexedDB'), []);
    assert.match(await read('src/contexts/ModeContext.tsx'), /'chimera-mode'/);
    assert.match(privacy, /chimera-mode/);
    assert.match(await read('src/lib/panelPrefs.ts'), /'chimera\.chat\.panel\.open'/);
    assert.match(privacy, /chimera\.chat\.panel\.open/);
    assert.match(await read('src/lib/chatLook.ts'), /'chimera\.chat\.look'/);
    assert.match(privacy, /chimera\.chat\.look/);

    // No analytics or advertising libraries, no third-party scripts or styles in the page.
    const pkg = JSON.parse(await read('package.json'));
    const deps = Object.keys({ ...pkg.dependencies, ...pkg.devDependencies }).join(' ');
    assert.ok(!/analytics|sentry|posthog|mixpanel|hotjar|gtag|plausible|segment|amplitude|fullstory/i.test(deps), 'a tracking library was added: update the Privacy Policy (cookies and sharing)');
    const html = await read('index.html');
    assert.ok(!/<script[^>]+src="https?:/i.test(html) && !/<link[^>]+href="https?:\/\/(?!www\.chimera)/i.test(html.replace(/rel="canonical"[^>]*>/, '')), 'third-party resources in index.html');

    // External services called by the server code: exactly the ones the Privacy Policy lists.
    const apiFiles = [];
    const walkApi = async (dir) => {
      for (const entry of await readdir(new URL(dir, root), { withFileTypes: true })) {
        if (entry.isDirectory()) await walkApi(`${dir}${entry.name}/`);
        else if (/\.ts$/.test(entry.name)) apiFiles.push(`${dir}${entry.name}`);
      }
    };
    await walkApi('api/');
    const hosts = new Set();
    for (const f of apiFiles) for (const m of (await read(f)).matchAll(/https?:\/\/([a-z0-9.-]+)/gi)) hosts.add(m[1]);
    hosts.delete('www.chimera.it.com');
    assert.deepEqual([...hosts].sort(), ['api.resend.com', 'generativelanguage.googleapis.com', 'openrouter.ai'], 'a new external service is called: add it to the Privacy Policy');
    assert.match(await read('api/create-shards-checkout.ts'), /from 'stripe'/);
    for (const name of ['Google', 'OpenRouter', 'Stripe', 'Supabase', 'Vercel', 'Resend']) assert.match(privacy, new RegExp(name));

    // The credits rules the product states on its own pages are in the Terms.
    const shardsPage = await read('src/pages/ShardsPage.tsx');
    assert.match(shardsPage, /non-transferable, non-withdrawable/);
    assert.match(terms, /cannot be transferred to another member/); assert.match(terms, /cannot convert SHARDS into VELLUM/);
    assert.match(await read('src/pages/VellumPage.tsx'), /cannot be transferred, withdrawn, or converted into SHARDS/);
  } finally { await close(); }
});

test('both documents render: banner, contents that point at real sections, visible TODO and confirm marks, and no raw markup', async () => {
  const { get, TERMS, PRIVACY, collectMarkers, close } = await load();
  try {
    // The same React instance must serve the page and this test, so these come from node itself, not from Vite.
    const react = await import('react');
    const { renderToStaticMarkup } = await import('react-dom/server');
    const { MemoryRouter } = await get('react-router-dom');
    const { LegalDocumentView } = await get('/src/components/legal/LegalDocumentView.tsx');
    for (const [doc, other] of [[TERMS, { to: '/privacy', label: 'Privacy Policy' }], [PRIVACY, { to: '/terms', label: 'Terms of Service' }]]) {
      const html = renderToStaticMarkup((react.default ?? react).createElement(MemoryRouter, null, (react.default ?? react).createElement(LegalDocumentView, { doc, other })));
      assert.ok(html.includes('DRAFT, NOT YET IN FORCE'), doc.title);
      assert.ok(html.includes(`<h1`) && html.includes(doc.title));
      const ids = [...html.matchAll(/<h2 id="([^"]+)"/g)].map((m) => m[1]);
      assert.deepEqual(ids, doc.sections.map((s) => s.id), `${doc.title}: one heading per section`);
      for (const id of ids) assert.ok(html.includes(`href="#${id}"`), `${doc.title}: contents link to ${id}`);
      assert.ok(html.includes('data-legal="todo"') && html.includes('data-legal="confirm"'));
      assert.ok(!html.includes('{{') && !html.includes('}}'), `${doc.title}: raw placeholder markup leaked`);
      assert.ok(!/\*\*[^*]/.test(html.replace(/<[^>]+>/g, '')), `${doc.title}: raw bold markup leaked`);
      assert.ok(html.includes(`href="${other.to}"`), 'links to the other document');
      const m = collectMarkers(doc);
      assert.ok(html.includes(`${m.openTodoKeys.length} details and ${m.confirmCount} choices are open`));
    }
  } finally { await close(); }
});

test('the open-questions list names every placeholder (regenerate it with npm run legal:questions)', async () => {
  const { PLACEHOLDERS, close } = await load();
  try {
    const md = await read('docs/legal/OPEN_QUESTIONS.md');
    for (const key of Object.keys(PLACEHOLDERS)) assert.ok(md.includes(`\`${key}\``), `docs/legal/OPEN_QUESTIONS.md is out of date: ${key} is missing`);
  } finally { await close(); }
});
