#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_dir"

ref_file="supabase/.temp/project-ref"
if [[ -f "$ref_file" ]]; then
  echo "Refusing to continue: this checkout is linked to a hosted Supabase project." >&2
  echo "Run 'supabase unlink' before using the local-only commands." >&2
  exit 1
fi

require_docker() {
  if ! docker info >/dev/null 2>&1; then
    echo "Docker Desktop is not running. Open Docker Desktop, then try again." >&2
    exit 1
  fi
}

write_frontend_env() {
  local status_json
  status_json="$(supabase status -o json)"
  STATUS_JSON="$status_json" node <<'NODE'
const fs = require('node:fs');
const status = JSON.parse(process.env.STATUS_JSON);
if (!/^http:\/\/(127\.0\.0\.1|localhost):54321$/.test(status.API_URL)) {
  throw new Error(`Refusing non-local Supabase URL: ${status.API_URL}`);
}
const publicEnv = [
  '# Generated by scripts/supabase-local.sh. Local development only.',
  `VITE_SUPABASE_URL=${status.API_URL}`,
  `VITE_SUPABASE_ANON_KEY=${status.ANON_KEY}`,
];

const preservedChimeraKeys = [
  'GEMINI_API_KEY_SERVER',
  'GEMINI_API_KEY',
  'OPENROUTER_API_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
];

function readExistingEnv(path) {
  if (!fs.existsSync(path)) return new Map();
  return new Map(
    fs.readFileSync(path, 'utf8')
      .split(/\r?\n/)
      .map((line) => line.match(/^([A-Z0-9_]+)=(.*)$/))
      .filter(Boolean)
      .map((match) => [match[1], match[2]]),
  );
}

fs.writeFileSync('apps/whisprr/.env.local', `${publicEnv.join('\n')}\n`, { mode: 0o600 });

const chimeraEnv = readExistingEnv('apps/chimera/.env.local');
const chimeraLines = [...publicEnv];
for (const key of preservedChimeraKeys) {
  if (chimeraEnv.has(key) && chimeraEnv.get(key)) {
    chimeraLines.push(`${key}=${chimeraEnv.get(key)}`);
  }
}

fs.writeFileSync('apps/chimera/.env.local', `${chimeraLines.join('\n')}\n`, { mode: 0o600 });
NODE
  echo "Generated local frontend environments and preserved existing CHIMERA server-only AI keys."
}

action="${1:-status}"
case "$action" in
  start)
    require_docker
    supabase start
    write_frontend_env
    ;;
  stop)
    supabase stop
    ;;
  status)
    supabase status
    ;;
  reset)
    require_docker
    supabase db reset --local --no-seed
    write_frontend_env
    ;;
  restore-backup)
    require_docker
    python3 scripts/restore-whisprr-local-backup.py "${2:-}"
    write_frontend_env
    ;;
  test)
    require_docker
    write_frontend_env
    python3 scripts/test-whisprr-local.py
    ;;
  test-chimera)
    require_docker
    write_frontend_env
    python3 scripts/test-chimera-local.py
    ;;
  functions)
    require_docker
    if [[ ! -f supabase/.env.local ]]; then
      echo "Create supabase/.env.local from supabase/.env.example first." >&2
      exit 1
    fi
    supabase functions serve --env-file supabase/.env.local
    ;;
  *)
    echo "Usage: $0 {start|stop|status|reset|restore-backup [path]|test|test-chimera|functions}" >&2
    exit 2
    ;;
esac
